/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simulacro;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void probar_convertir_min_sec(){
        App probar = new App();
        int segundos = probar.Convertir_min_sec(100);

        //se evalua el valor esperado con assertEquals
        assertEquals(6000, segundos, "El valor de segundos esperado para 100 minutos son 6000 segundos");

    }

    @Test void probar_iguales(){
        App probar = new App();
        boolean iguales = probar.Validar_iguales((byte)100, (byte)100);
        assertTrue(iguales,"La función debería devolver un True");
    }

    @Test void probar_calcular_potencia(){
        App probar = new App();
        float potencia = probar.Calcular_potencia((short)300,(byte)10);

        //se evalua el valor esperado con assertEquals
        assertEquals(3000.0, potencia, "la potencia esperada para un voltaje de 300 y una corriente de 10, es 3000");

    }

    

}
