name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Prueba_sim
      id: prueba_sim
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Prueba_sim
        setup-command: ''
        command: gradle test
        timeout: 5
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRUEBA_SIM_RESULTS: "${{steps.prueba_sim.outputs.result}}"
      with:
        runners: prueba_sim
